### ISSUE TITLE
Wondering why this is happening???

### ISSUE THREAD

**Issue by stanleyjoy** [fehaar/FFWD#76]
We are working on a new project. This one has 3 cams with various culling mask. I get a null reference at 
The issue is pointing out to renderItem.cs

System.NullReferenceException was unhandled
  Message=NullReferenceException
  StackTrace:
       at PressPlay.FFWD.Components.RenderItem.UpdateCullingInfo(Camera cam)
       at PressPlay.FFWD.Components.Camera.Culling()
       at PressPlay.FFWD.Application.Draw(GameTime gameTime)
       at Microsoft.Xna.Framework.Game.Draw(GameTime gameTime)
       at FFWD.Unity.Tests.Game1.Draw(GameTime gameTime)
       at Microsoft.Xna.Framework.Game.DrawFrame()
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.MobileGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.MobileGameHost.gameLoopTimer_Tick(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.DispatcherTimerWin32.TimerElapsed(IntPtr hWnd, UInt32 uMsg, IntPtr nIDEvent, UInt32 uTime)

**Comment by fehaar** [comment]
Proably an issue with the unfinished "new" rendering pipeline. Set the UseFallbackRendering flag in ApplicationSettings to true.

**Comment by stanleyjoy** [comment]
Sorry I completely forgot about that thing.
Dammit
Stan
